name: crisp
description: Connect with Crisp Chat, register a user to chat (or not) and render a chat widget.
version: 0.1.3
homepage: https://github.com/lunahq/flutter-crisp

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.oiluna.crisp
    pluginClass: CrispPlugin

dependency_overrides:
  flutter_webview_plugin:
    git:
      url: https://github.com/ramah/flutter_webview_plugin.git
      ref: master